name: build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Extract deployment environment
        id: deploy_env
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "environment=production" >> $GITHUB_OUTPUT
          fi
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: make build
      - name: Deploy
        run: make deploy/${{ steps.deploy_env.outputs.environment }}
        if: steps.deploy_env.outputs.environment != ''
